export const SAN_PEDRO_BARANGAYS = [
  "Bagong Silang",
  "Calendola",
  "Chrysanthemum",
  "Ciudad Real",
  "Cuyab",
  "Fatima",
  "G.S.I.S.",
  "Landayan",
  "Langgam",
  "Laram",
  "Maharlika",
  "Magsaysay",
  "Narra",
  "Nueva",
  "Pacita Complex I",
  "Pacita Complex II",
  "Poblacion",
  "Riverside",
  "Rosario",
  "Sacred Heart",
  "Sampaguita Village",
  "San Antonio",
  "San Lorenzo Ruiz",
  "San Roque",
  "San Vicente",
  "Santo Niño",
  "United Bayanihan",
  "United Better Living"
];
